-- V4: the transactional outbox.
--
-- THE PROBLEM THIS SOLVES: THE DUAL WRITE
--
-- An adjustment lands. Two things must happen: the account's buffer changes in
-- the database, and the rest of the platform is told about it. The obvious code
-- is two statements in a row:
--
--     accounts.updateLiquidityBuffer(...);      -- database
--     kafka.send("buffer-changed", event);      -- network
--
-- That is a DUAL WRITE, and it is broken in both directions:
--
--   * If the database commits and the Kafka send fails - broker down, network
--     blip, the process is killed between the two lines - the money moved and
--     nobody was told. The position engine's view of the world is now wrong,
--     silently, forever.
--
--   * If the Kafka send succeeds and the transaction then rolls back, the
--     platform acts on a change that never happened.
--
-- @Transactional does not help. Kafka is not enlisted in the database
-- transaction, so a rollback cannot un-send a message. Two-phase commit across
-- a database and a broker is theoretically possible, practically miserable, and
-- essentially nobody does it.
--
-- THE OUTBOX
--
-- Do not send anything. Write the event into THIS table, in the SAME
-- transaction as the business change. One transaction, one atomic outcome:
-- either the buffer changed and the event exists, or neither happened.
--
-- A separate relay then reads unpublished rows and sends them to Kafka. If the
-- relay dies mid-flight, the row is still here and the next run sends it.
--
-- WHAT THIS BUYS AND WHAT IT COSTS
--
-- Buys: the database and the event stream can never disagree.
-- Costs: delivery is AT-LEAST-ONCE. The relay can publish a message and die
-- before recording that it did, so the next run publishes it again. That is not
-- a flaw to be fixed - it is the contract. Consumers must be idempotent, which
-- is exactly the mechanism you built in Layer 3, now on the receiving end.
--
-- ORACLE NOTE (ADR 0004): TEXT becomes CLOB, TIMESTAMPTZ becomes TIMESTAMP WITH
-- TIME ZONE, GENERATED BY DEFAULT AS IDENTITY works from 12c onward, and the
-- partial index below has no direct equivalent - see the comment on it.

CREATE TABLE outbox_event (
    -- A generated, monotonically increasing key. It is the ORDERING column, not
    -- just an identifier: the relay reads "oldest unpublished first", and
    -- Kafka's own ordering guarantee is per-partition, so the order we send in
    -- is the order a consumer sees for a given account.
    --
    -- Note the contrast with idempotency_record, whose key is ASSIGNED by the
    -- client and therefore needed Persistable to stop Spring Data calling merge
    -- instead of persist. Here the id is generated, so save() does the right
    -- thing with no help. Same framework, opposite behaviour, and the deciding
    -- factor is who chooses the identifier.
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,

    -- A stable, business-level identity for the event itself, carried in the
    -- payload and used by consumers to deduplicate. Separate from the primary
    -- key on purpose: the primary key is ours and local, the event id is the
    -- one that travels and that another service will store.
    event_id        VARCHAR(36)  NOT NULL,

    -- Which kind of thing changed, and which one. Together these are the
    -- aggregate: the consistency boundary the event belongs to.
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,

    -- What happened, in past tense. Events are facts, not commands.
    event_type      VARCHAR(64)  NOT NULL,

    -- The destination is stored with the row rather than hard-coded in the
    -- relay, so one relay can serve many event types and topics without
    -- knowing anything about the domain.
    topic           VARCHAR(128) NOT NULL,

    -- The Kafka message key. Kafka guarantees ordering WITHIN a partition, and
    -- routes by hash of the key, so every event for one account lands on one
    -- partition and is therefore delivered in order relative to its siblings.
    -- Get this wrong and "buffer set to 20m" can overtake "buffer set to 15m".
    partition_key   VARCHAR(64)  NOT NULL,

    payload         TEXT         NOT NULL,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- NULL means "not yet sent". This column is the entire queue state.
    published_at    TIMESTAMPTZ,

    CONSTRAINT pk_outbox_event PRIMARY KEY (id),

    -- Not decoration. It is the backstop that makes a bug in the writer - the
    -- same event recorded twice - fail loudly here rather than turn into two
    -- messages on the topic.
    CONSTRAINT uq_outbox_event_event_id UNIQUE (event_id)
);

-- A PARTIAL index: it contains only the rows the relay cares about.
--
-- This matters more than it looks. The table is append-only and will hold
-- millions of published rows; the unpublished set is normally a handful. A
-- plain index on published_at would grow with the whole table and the relay's
-- query would get slower forever. This index stays roughly the size of the
-- backlog no matter how large the table becomes.
--
-- Oracle has no partial indexes. The usual equivalent is a function-based index
-- on CASE WHEN published_at IS NULL THEN id END, which Oracle does not store
-- rows for when the expression is NULL - the same effect by a different route.
-- Worth knowing; "it depends on the database" is a better answer than a shrug.
CREATE INDEX idx_outbox_event_unpublished
    ON outbox_event (id)
    WHERE published_at IS NULL;

-- Supports the eventual archival job (Layer 7) that deletes rows published
-- more than N days ago. Without pruning this table is a slow-motion outage.
CREATE INDEX idx_outbox_event_published_at ON outbox_event (published_at);

COMMENT ON TABLE outbox_event IS
    'Transactional outbox: domain events written in the same transaction as the business change';
COMMENT ON COLUMN outbox_event.partition_key IS
    'Kafka message key; determines partition and therefore per-key ordering';
COMMENT ON COLUMN outbox_event.published_at IS
    'NULL until the relay has received an acknowledgement from Kafka';
